name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - build: windows
            os: windows-latest
            rust: beta
            target: x86_64-pc-windows-msvc
            update_rustup: true
          - build: windows
            os: windows-latest
            rust: beta
            target: x86_64-pc-windows-msvc
            update_rustup: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Log rustup version
        run: |
          rustup --version

      - name: Show rustup toolchains
        run: |
          rustup show

      - name: Update rustup
        if: matrix.update_rustup
        run: |
          rustup --verbose self update

      - name: Install Rust
        run: |
          rustup --verbose install ${{ matrix.rust }}
          rustup --verbose default ${{ matrix.rust }}

      - name: Log rustup version
        run: |
          rustup --version

      - name: Show rustup toolchains
        run: |
          rustup show

      - name: Check versions
        run: |
          cargo --version
          rustc --version
